samples = [("cal", "spn"), ("cal", "eru"), ("cal", "ruf"), ("cal", "umb"), ("cal", "vie")]

rule all:
    input:
        # test window intersect
        "results/test_intersect/pcadapt/fst.svg",
        "results/test_intersect/goi_intersection_heatmap.svg",
        "results/test_intersect/all_tests_intersection.svg",
        ## PicMin
        "results/picmin/pcadapt/picmin_results.padj.jpeg",
        ## gene func
        "results/gene_func_ana/pcadapt_intersection/fst_enrichment.jpg",
        "results/gene_func_ana/pcadapt/enrichment.jpg",
        "results/gene_func_ana/mktest/enrichment.jpg",
        "results/gene_func_ana/pcadapt_mktest/enrichment.jpg",
        "results/gene_func_ana/picmin/enrichment.jpg",
        # superexact/upset
        "results/superexact/pcadapt_intersection/gene.pdf",
        "results/superexact/pcadapt/gene.pdf",
        "results/superexact/pcadapt_mktest/gene.pdf",
        

# FST
include: "rules/vcf_preprocessing.smk"
include: "rules/fst_step_window.smk"
# MKT
include: "rules/vcf_annotation.smk" 
include: "rules/vcf_pop_freq_subset.smk"
include: "rules/mk_test_stat.smk"
# Tajima'D and PI
include: "rules/ind_stats.smk"
include: "rules/pair_stats.smk"
# pcadapt
include: "rules/pcadapt_scan.smk"
include: "rules/pcadapt_peak_finder.smk"
# pi windows
include: "rules/bed_filter_and_outlier.smk"
include: "rules/species_pi_window_intersect.smk"
include: "rules/tree_pi_window_intersect.smk"
include: "rules/test_window_intersect.smk"
# PicMin
include: "rules/picmin_analysis.smk"
# gene func
include: "rules/gene_functional_annotation.smk"
include: "rules/gene_functional_analysis.smk"
# superexact/upset
include: "rules/parallel_adaptation.smk"