PAIRS = [("fla", "umb"), ("fla", "spn"), ("cal", "spn")]

rule all:
    input:
        expand("results/fst_plots/pair_{pair[0]}_{pair[1]}.{n}.fst.jpg", pair=PAIRS, n=range(10000, 30000, 10000))

#include: "rules/fst_sliding_window.smk"
include: "rules/fst_step_window.smk"
include: "rules/vcf_preprocessing.smk"